### ISSUE TITLE
Rename release on github to align with version name on maven

### ISSUE THREAD

**Issue by Dambakk** [fornewid/placeholder#1]
Hi! Thanks for extracting this as a separate library!

While migrating I struggled to resolve the dependencies, and it was only when I opened the maven source (https://mvnrepository.com/artifact/io.github.fornewid/placeholder-material) that I noticed that I should use `1.0.0-rc` as version code instead of `v1.0.0-rc` which is the name of the release here on github (https://github.com/fornewid/placeholder/releases). Also the badge in the readme has the `v` prefix. It would be very helpful if these aligned with the version published to maven. Thanks!

**Comment by fornewid** [comment]
Thank you for your opinion.
I can remove **"v"** prefix of release on github easily. (already fix that)

But the badge in the readme is difficult to fix.
Because it is an auto version badge.

> https://img.shields.io/maven-central/v/io.github.fornewid/placeholder-foundation
> is equals to
> <img alt="Maven Central" src="https://img.shields.io/maven-central/v/io.github.fornewid/placeholder-foundation">

This is the same for other libraries, so I'm trying to keep it.
Have a nice day. :)
