### ISSUE TITLE
Allow to set only one placeholder for container

### ISSUE THREAD

**Issue by maicol07** [fornewid/placeholder#5]
Hi,
can you add support for containers composables (like Columns)?
Currently, placeholdering a column means applying a placeholder to the entire column block (and results in a single placeholder block) and it doesn't show what's inside (due to this, placeholder must be applied to every child element). It would be great if the shimmer applied to an element would understand what are their children and apply it to them
There is another shimmer library which does it successfully, but it doesn't provide all the effects your library has: https://github.com/ValeryPonomarenko/compose-shimmer
Thanks!

**Comment by fornewid** [comment]
@maicol07 
Thanks for suggesting these interesting ideas.

Looking at the principles of the [ValeryPonomarenko/compose-shimmer](https://github.com/ValeryPonomarenko/compose-shimmer) project,
it uses `BlendMode.DstIn` with alpha after drawContent() is called. (a.k.a [`PorterDuff.Mode`](https://developer.android.com/reference/android/graphics/PorterDuff.Mode))
So child composables are just exposed without placeholder.
(That is, it supports the shimmer effect only.)

In a more detailed comparison:
- [fornewid/placeholder](https://github.com/fornewid/placeholder) is is drawn without calling `drawContent()`.
- [ValeryPonomarenko/compose-shimmer](https://github.com/ValeryPonomarenko/compose-shimmer) always call `drawContent()`.

So it seems unavailable for actual content composable. 🤔 

If you need to declare a placeholder screen,
I think, writing code is not difficult even if you call `placeholder()`.

**Comment by maicol07** [comment]
Ok, thank you! I'll close this for now
